#![forbid(unsafe_code)]

pub mod app_ingress;
pub mod device_artifact_sync;
pub mod ph1_voice_id;
pub mod ph1bcast;
pub mod ph1builder;
pub mod ph1c;
pub mod ph1cache;
pub mod ph1capreq;
pub mod ph1context;
pub mod ph1cost;
pub mod ph1d;
pub mod ph1delivery;
pub mod ph1diag;
pub mod ph1doc;
pub mod ph1e;
pub mod ph1emocore;
pub mod ph1emoguide;
pub mod ph1endpoint;
pub mod ph1explain;
pub mod ph1export;
pub mod ph1f;
pub mod ph1feedback;
pub mod ph1gov;
pub mod ph1j;
pub mod ph1k;
pub mod ph1kg;
pub mod ph1kms;
pub mod ph1know;
pub mod ph1l;
pub mod ph1lang;
pub mod ph1learn;
pub mod ph1lease;
pub mod ph1link;
pub mod ph1listen;
pub mod ph1m;
pub mod ph1multi;
pub mod ph1n;
pub mod ph1onb;
pub mod ph1os;
pub mod ph1pae;
pub mod ph1pattern;
pub mod ph1persona;
pub mod ph1policy;
pub mod ph1position;
pub mod ph1prefetch;
pub mod ph1pron;
pub mod ph1prune;
pub mod ph1quota;
pub mod ph1rem;
pub mod ph1rll;
pub mod ph1sched;
pub mod ph1search;
pub mod section40_exit;
pub mod ph1srl;
pub mod ph1summary;
pub mod ph1tenant;
pub mod ph1tts;
pub mod ph1vision;
pub mod ph1w;
pub mod ph1work;
pub mod ph1write;
pub mod ph1x;
pub mod simulation_executor;

pub fn hello_compile() -> &'static str {
    "hello compile"
}
